### ISSUE TITLE
 questions of the calculation of Fe XVII

### ISSUE THREAD

**Issue by FFWu7** [ud-pci/pCI#53]
Hi there,

I have two questions about the BASS.INP input file provided in the documentation (pCI/docs/examples/hci.rst) for Fe XVII calculations：

In the example BASS.INP (b_m_2.inp) file, the number of valence and virtual orbitals is listed as Nv=194. Given that the maximum principal quantum number is 24, I calculated the total number of orbitals for the s, p, d, f, and g shells to be 192 (22, 44, 44, 42, and 40 respectively). Could you help clarify where this discrepancy might come from?

The BASS.INP input file for the CI-MBPT package [Computer Physics Communications 195 (2015) 199–213] includes a parameter called “auto.” When set to 1, it allows automatic generation of the orbital list by specifying only the orbital quantum number  of last partial wave ("lmax") and the maximum principal quantum number for each orbital. However, I noticed that the Fe XVII example in pCI/docs/examples/hci.rst does not include the "auto" parameter. Does this mean the orbitals must be manually listed one by one?

Thank you very much!

Best regards,
FFWu

**Comment by ccheung93** [comment]
Hi FFWu,

Sorry - there is a typo in the documentation. You are correct, the total number of orbitals should be 192. I will fix the documentation. Thank you for pointing it out.

In the 2015 package, the parameter "auto" is included to automatically generate the orbital list for simpler cases. 
This can certainly still be used as before, if one wishes to construct orbitals in the default manner from DF orbitals.
However in the Fe16+ example, we use a more complex method, where orbitals are constructed at different steps of hfd. Here, we have to explicitly list the virtual orbitals and define how they are constructed (see valence+virtual orbitals #6-12, 20-21 with the key '3' in the documentation).

Best,
Charles

**Comment by FFWu7** [comment]
Thank you so much for your helpful reply.
