### ISSUE TITLE
Issue with Building pCI on HPC Clusters

### ISSUE THREAD

**Issue by FFWu7** [ud-pci/pCI#55]
Hi there,

I build pCI on HPC clusters using CMake, I execute `FC=ifort cmake -DMPI_HOME=${OPENMPI_PREFIX} -DCMAKE_INSTALL_PREFIX=$(pwd)/../ ..` and `make`， and I changing `-mkl=sequential` to `-qmkl=sequential`， as well as `-mkl=parallel` to `-qmkl=parallel` in the root CMakeLists.txt, the following error appeared:

Scanning dependencies of target pbasc
[ 50%] Building Fortran object src/CMakeFiles/pbasc.dir/pbasc.f90.o
[ 51%] Linking Fortran executable pbasc
CMakeFiles/pbasc.dir/pbasc.f90.o: In function `MAIN__':
/public1/home/scb3494/soft/pCI/src/pbasc.f90:16: undefined reference to `mpi_init_f08_'
/public1/home/scb3494/soft/pCI/src/pbasc.f90:18: undefined reference to `mpi_f08_compile_constants_mp_mpi_comm_world_'
/public1/home/scb3494/soft/pCI/src/pbasc.f90:18: undefined reference to `mpi_comm_rank_f08_'
/public1/home/scb3494/soft/pCI/src/pbasc.f90:20: undefined reference to `mpi_f08_compile_constants_mp_mpi_comm_world_'
/public1/home/scb3494/soft/pCI/src/pbasc.f90:20: undefined reference to `mpi_comm_size_f08_'
/public1/home/scb3494/soft/pCI/src/pbasc.f90:25: undefined reference to `mpi_f08_compile_constants_mp_mpi_real_'
/public1/home/scb3494/soft/pCI/src/pbasc.f90:57: undefined reference to `mpi_finalize_f08_'
CMakeFiles/pbasc.dir/pbasc.f90.o: In function `pbasc_IP_allocaterintarrays_':
/public1/home/scb3494/soft/pCI/src/pbasc.f90:709: undefined reference to `mpi_f08_compile_constants_mp_mpi_integer_'
/public1/home/scb3494/soft/pCI/src/pbasc.f90:709: undefined reference to `mpi_f08_compile_constants_mp_mpi_comm_world_'
/public1/home/scb3494/soft/pCI/src/pbasc.f90:709: undefined reference to `mpi_bcast_f08ts_'
... ...
... ...
libpci_common.a(mpi_utils.f90.o): In function `mpi_utils_mp_allreducer_':
mpi_utils.f90:(.text+0x10e3): undefined reference to `MPIR_F08_MPI_IN_PLACE'
mpi_utils.f90:(.text+0x116f): undefined reference to `mpi_allreduce_f08ts_'
mpi_utils.f90:(.text+0x1223): undefined reference to `MPIR_F08_MPI_IN_PLACE'
mpi_utils.f90:(.text+0x1288): undefined reference to `mpi_allreduce_f08ts_'
make[2]: *** [src/pbasc] Error 1
make[1]: *** [src/CMakeFiles/pbasc.dir/all] Error 2
make: *** [all] Error 2

Could you please advise on how to resolve this issue?

Thank you very much for your help.

Best regards,
FFWu

**Comment by ccheung93** [comment]
Hi FFWu,

This problem typically occurs when there's a mismatch between the compiler loaded in your environment with the one used to compile OpenMPI. First, set the flag `-DMPI_HOME=<path to OpenMPI directory>` and see if it is able to build. If not, you can try specifying the compilers as so:
```
FC=ifort cmake -DCMAKE_Fortran_COMPILER=ifort -DMPI_HOME=/usr/lib64/openmpi -DMPI_Fortran_COMPILER=mpifort -DCMAKE_INSTALL_PREFIX=$(pwd)/../ ..
```

Make sure to set the `-DMPI_HOME` to the path of your OpenMPI root directory.

Best,
Charles

**Comment by FFWu7** [comment]
Thank you so much for your assistance, the issue has been successfully resolved.

Best regards,
FFWu
